//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartridgeReplacement_Log
    {
        public int Id { get; set; }
        public Nullable<int> OldCartridgeId { get; set; }
        public int NewCartridgeId { get; set; }
        public int PrinterId { get; set; }
        public int EmployeeLitId { get; set; }
        public int ReasonId { get; set; }
        public string Comment { get; set; }
    
        public virtual Printer Printer { get; set; }
        public virtual ReasonForRelpacement ReasonForRelpacement { get; set; }
    }
}
