//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.GivedDevices = new HashSet<GivedDevices>();
        }
    
        public int Id { get; set; }
        public int DeviceTypeId { get; set; }
        public string Characteristics { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> DeviceModelId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual DeviceModel DeviceModel { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Room Room { get; set; }
        public virtual StatusDevice StatusDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GivedDevices> GivedDevices { get; set; }
        public virtual Laptop Laptop { get; set; }
        public virtual Printer Printer { get; set; }
    }
}
