//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiveRequest_Log
    {
        public int Id { get; set; }
        public string WhoGivedLaptops { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string Laptops { get; set; }
        public string Comment { get; set; }
    }
}
