//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GivedDevices
    {
        public int Id { get; set; }
        public int GivedEmployeId { get; set; }
        public System.DateTime GivedDate { get; set; }
        public string Comment { get; set; }
        public int GivedDeviceId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
