//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LITEntities : DbContext
    {
        public LITEntities()
            : base("name=LITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Cartridge> Cartridge { get; set; }
        public virtual DbSet<CartridgeModel> CartridgeModel { get; set; }
        public virtual DbSet<CartridgeReplacement_Log> CartridgeReplacement_Log { get; set; }
        public virtual DbSet<CartridgeStatus> CartridgeStatus { get; set; }
        public virtual DbSet<CartridgeType> CartridgeType { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceModel> DeviceModel { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeePosition> EmployeePosition { get; set; }
        public virtual DbSet<GivedDevices> GivedDevices { get; set; }
        public virtual DbSet<Laptop> Laptop { get; set; }
        public virtual DbSet<PerfomanceRate> PerfomanceRate { get; set; }
        public virtual DbSet<Printer> Printer { get; set; }
        public virtual DbSet<PrinterStatus> PrinterStatus { get; set; }
        public virtual DbSet<ReasonForRelpacement> ReasonForRelpacement { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<StatusDevice> StatusDevice { get; set; }
    }
}
