//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printer()
        {
            this.CartridgeReplacement_Log = new HashSet<CartridgeReplacement_Log>();
        }
    
        public int Id { get; set; }
        public int NumberOfRepairs { get; set; }
        public Nullable<int> CartridgeId { get; set; }
        public int PrinterStatusId { get; set; }
        public System.DateTime CartridgeReplacementDate { get; set; }
        public string PrinterDocumentsList { get; set; }
    
        public virtual Cartridge Cartridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartridgeReplacement_Log> CartridgeReplacement_Log { get; set; }
        public virtual Device Device { get; set; }
        public virtual PrinterStatus PrinterStatus { get; set; }
    }
}
